preco_atual = float(input("Digite o preço atual do produto: "))
media_mensal = float(input("Digite a média de vendas mensal do produto: "))

if preco_atual < 30.00, media_mensal < 500
    print("O novo preço do produto deve ser de R$", preco_atual + (preco_atual . 0.1))
 elif preco_atual >= 30.00 & < 80.00, media_mensal >= 500 & < 1000
    print("O novo preço do produto deve ser de R$", preco_atual + (preco_atual . 0.15))
 elif preco_atual >= 80.00 & >= 1000
    print("O novo preço do produto deve ser de R$", preco_atual - (preco_atual . 0.05))
 else
    print("O preço do produto deve continuar o mesmo.")