investimento = int(input("Selecione o tipo de investimento (digite 1 para poupança ou 2 para renda fixa):"))
valor_investido = float(input("Digite o valor investido:"))

if investimento == 1
    print("O valor corrigido em 30 dias será de R$", valor_investido + (valor_investido . 0.03))
 elif investimento == 2
    print("O valor corrigido em 30 dias será de R$", valor_investido + (valor_investido . 0.05))
 else
    print("Tipo de investimento não reconhecido.")